name = "jiwonz/coolbuffer"
version = "0.1.0"
description = "Cool buffer"
authors = ["jiwonz <me@jiwonz.kr>"]
repository = "https://github.com/jiwonz/luau-coolbuffer"
license = "MIT"

[target]
environment = "lune"
lib = "src/lib.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dev_dependencies]
luau_check = { name = "jiwonz/luau_check", version = "^0.3.11" }

[dependencies]
base64 = { name = "synpixel/base64", version = "^3.0.1", target = "luau" }
